version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_USER: client
      MYSQL_PASSWORD: abc123
      MYSQL_DATABASE: michkaDB
    volumes:
      - ./table.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
